module.exports = {
    GOOGLE_AUTH_ID: process.env.GOOGLE_AUTH_ID,
    GOOGLE_AUTH_SECRET: process.env.GOOGLE_AUTH_SECRET,
    FACEBOOK_AUTH_ID: process.env.FACEBOOK_AUTH_ID,
    FACEBOOK_AUTH_SECRET: process.env.FACEBOOK_AUTH_SECRET,
    STRIPE_PUBLISHABLE_KEY: process.env.STRIPE_PUBLISHABLE_KEY,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    MONGO_URI: process.env.MONGO_URI,
    COOKIE_KEY: process.env.COOKIE_KEY,
};
